services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  app:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    command: ["./scripts/init_app.sh"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    depends_on:
      - db

  tests:
      build:
        context: .
        dockerfile: Dockerfile
      env_file: .env
      volumes:
        - .:/app/
      depends_on:
        - db
      command: /bin/sh -c "pytest --cov=wishlist tests/"
